version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: quack_backend
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-service-account.json
    volumes:
      - ./gcp-service-account.json:/app/gcp-service-account.json:ro
    expose:
      - "3000"
    restart: always

  frontend:
    build:
      context: .
    container_name: quack_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
